const presets = {
    "Saw Lead": {
        "volume1": "0.2",
        "waveform1": "sawtooth",
        "xEnv1": "0",
        "volume2": "0.2",
        "waveform2": "sawtooth",
        "xEnv2": "0",
        "noiseVolume": "0.02",
        "semitone": "-12",
        "detune": "-14",
        "attack": "0",
        "decay": "0.1",
        "sustain": "0.5",
        "release": "0.1",
        "filterType": "lowpass",
        "filterFrequency": "1000",
        "delayTime": "0.15",
        "delayDecay": "0.41",
        "distortionAmount": "0.24"
    },
    "wet square NES-ish": {
        "volume1": "0.34",
        "waveform1": "square",
        "xEnv1": "0",
        "volume2": "0",
        "waveform2": "square",
        "xEnv2": "0",
        "noiseVolume": "0",
        "semitone": "0",
        "detune": "0",
        "attack": "0",
        "decay": "0",
        "sustain": "0.5",
        "release": "0",
        "filterType": "lowpass",
        "filterFrequency": "1000",
        "delayTime": "0.1",
        "delayDecay": "0.48",
        "distortionAmount": "0.11"
      },
      "base drum 1": {
        "volume1": "0.32",
        "waveform1": "triangle",
        "xEnv1": "8",
        "volume2": "0.32",
        "waveform2": "triangle",
        "xEnv2": "7",
        "noiseVolume": "0.33",
        "semitone": "-10",
        "detune": "-7",
        "attack": "0",
        "decay": "0",
        "sustain": "0.5",
        "release": "0.35",
        "filterType": "lowpass",
        "filterFrequency": "359",
        "delayTime": "0",
        "delayDecay": "0.33",
        "distortionAmount": "0.05"
      }
  };
  